name: Daily Limitless Sync

on:
  schedule:
    # Run at 11 PM UTC every day (adjust for your timezone)
    - cron: '0 23 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync-notes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # Fetch all history
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install requests
    
    - name: Fetch and save daily notes
      env:
        LIMITLESS_API_KEY: ${{ secrets.LIMITLESS_API_KEY }}
      run: |
        python << 'EOF'
        import os
        import json
        import requests
        from datetime import datetime
        from pathlib import Path
        
        # Fetch from Limitless API
        api_key = os.environ['LIMITLESS_API_KEY']
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        }
        
        # Adjust this URL based on actual Limitless API
        response = requests.get(
            "https://api.limitless.ai/v1/transcripts",
            headers=headers,
            params={"date": datetime.now().strftime('%Y-%m-%d')}
        )
        
        if response.status_code == 200:
            data = response.json()
            
            # Format the content
            date = datetime.now()
            content = f"""# Daily Notes - {date.strftime('%B %d, %Y')}
        
        **Date**: {date.strftime('%Y-%m-%d')}  
        **Day**: {date.strftime('%A')}  
        
        ---
        
        ## Transcript
        
        {json.dumps(data, indent=2)}
        
        ---
        
        *Automatically synced via GitHub Actions*
        """
            
            # Create file path
            year = date.strftime('%Y')
            month = date.strftime('%m-%B')
            filename = f"{date.strftime('%Y-%m-%d')}-notes.md"
            
            file_path = Path(year) / month / filename
            file_path.parent.mkdir(parents=True, exist_ok=True)
            
            # Write file
            with open(file_path, 'w') as f:
                f.write(content)
            
            print(f"Created {file_path}")
        else:
            print(f"API error: {response.status_code}")
            exit(1)
        EOF
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Add daily notes for $(date +'%Y-%m-%d')" && git push)
